version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: sistema_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_forte
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://admin:senha_forte@db/sistema_db
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
